add_subdirectory(softrend)
add_subdirectory(pentprim)
add_subdirectory(virtual_fb)
add_subdirectory(glrend)
if(AMIGA)
    add_subdirectory(3dfx_amiga)
endif()
target_link_libraries(brender-full INTERFACE softrend pentprim virtual_fb glrend )
if(AMIGA)
    target_link_libraries(brender-full INTERFACE 3dfx_amiga)
endif()
